imports:
  - path: github.com/sebousan/hugolify-theme-uncinqify
  - path: github.com/hugolify/hugolify-theme-docs
  - path: github.com/hugolify/hugolify-theme
  # - path: github.com/hugolify/hugolify-admin
